parameters:
  username:
    name: username
    description: Username to use for login.
    in: formData
    required: true
    type: string


components:
  securitySchemes:
    traderAuthorization:
      type: http
      description: 平台交易人驗證
      scheme: bearer
      bearerFormat: JWT